import {createAvatar} from './avatar.js';
import {preparePicture} from './picture-upload.js';
const $=id=>document.getElementById('profile-'+id);
let account=null,version=null,current=null,draft=null,retry=null,busy=false,epoch=0;
const visible=()=>location.hash.split('?')[0]==='#settings'&&!document.hidden&&navigator.onLine;
function controls(){const unavailable=busy||!account||!visible();$('file').disabled=unavailable;$('save').disabled=unavailable||!draft;$('remove').disabled=unavailable||!current;$('refresh').disabled=busy||!visible();}
function preview(){const avatar=createAvatar({...account?.participant,avatarVersion:current});if(draft){const img=document.createElement('img');img.src='data:image/jpeg;base64,'+draft.data;img.alt='Selected profile picture preview';avatar.replaceChildren(img);}$('preview').replaceChildren(avatar);controls();} // A new picture is only a preview until Save is pressed.
function clear(){epoch++;account=null;version=null;current=null;draft=null;retry=null;$('file').value='';$('preview').replaceChildren();$('status').textContent='Open Settings while signed in to manage your picture.';controls();}
async function request(input){const response=await fetch('./api/social/profile',{method:input?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(30000),headers:input?{'Content-Type':'application/json','X-CSRF-Token':account?.csrf??''}:{},...(input?{body:JSON.stringify(input)}:{})});let value;try{value=await response.json();}catch{throw Error(response.status===413?'The server rejected the upload size. Refresh the app and try again.':'The server could not save this picture. Please retry.');}
 if(!response.ok){if([401,403].includes(response.status))clear();if(response.status===409){retry=null;draft=null;account=null;controls();}throw Error(value.error||'Could not load your profile picture.');}return value;
} // Session and CSRF protect uploads; conflicting updates require Refresh before another save.
async function load(){if(busy||!visible())return;busy=true;controls();const ticket=epoch;try{const value=await request();if(ticket!==epoch)return;account=value;version=value.version;current=value.avatarVersion;draft=null;retry=null;preview();$('status').textContent=current?'Your current profile picture.':'Choose a picture to add to your profile.';}catch(error){if(visible())$('status').textContent=error.message;}finally{busy=false;controls();}}
const prepare=file=>preparePicture(file,{square:true}); // Fit camera originals into a small, square upload before saving.
$('file').addEventListener('change',async()=>{const file=$('file').files[0];$('file').value='';if(!file||busy||!account)return;busy=true;controls();const ticket=epoch;try{$('status').textContent='Resizing your picture...';const picture=await prepare(file);if(ticket!==epoch)return;draft=picture;retry=null;preview();$('status').textContent='Preview ready. Save to use this picture.';}catch(error){if(ticket===epoch)$('status').textContent=error.message;}finally{busy=false;controls();}});
async function save(remove=false){if(busy||!account)return;if(remove&&!confirm('Remove your profile picture?'))return;busy=true;controls();const ticket=epoch;try{if(!retry||Boolean(retry.picture)===remove)retry={requestId:crypto.randomUUID(),version,picture:remove?null:draft};const value=await request(retry);if(ticket!==epoch)return;account=value;version=value.version;current=value.avatarVersion;draft=null;retry=null;preview();$('status').textContent=remove?'Profile picture removed.':'Profile picture saved.';}catch(error){if(visible())$('status').textContent=error.message;}finally{busy=false;controls();}} // Reuse the same request after an uncertain response, so retries cannot overwrite a later change.
$('save').addEventListener('click',()=>void save());$('remove').addEventListener('click',()=>void save(true));$('refresh').addEventListener('click',()=>void load());
window.addEventListener('hashchange',()=>{clear();if(visible())void load();});window.addEventListener('little-log-signout',clear);window.addEventListener('offline',clear);window.addEventListener('online',()=>void load());
document.addEventListener('visibilitychange',()=>{clear();if(visible())void load();});window.addEventListener('storage',event=>{if((event.key==='lidoll.little-log.v1'||event.key===null)&&!event.newValue)clear();});
if(visible())void load();else controls();
